name: Release on Modrinth, CurseForge and Github
on: [pull_request, workflow_dispatch]

env:
  MINECRAFT_VERSION: 1.21.10
  JAVA_VERSION: 21

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Kira-NT/mc-publish@v3.3.0
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: Chilllyy
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: chilllyy
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on GitHub.
          github-token: ${{ secrets.GIT_TOKEN }}